CREATE TABLE USER
(ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(25)  NOT NULL,
SECOND_NAME VARCHAR(25) NOT NULL,
ACCOUNT_NUMBER INT,
PRIMARY KEY (ID));

INSERT INTO USER VALUES (1, 'John', 'Doe', '1234');
INSERT INTO USER VALUES (2, 'Jane', 'Doe', '1235');
INSERT INTO USER VALUES (3, 'Jim', 'Taylor', '1236');